# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_4vt2Mg34xvtty3dINe69b8oFn5TEGT
"""

pip freeze > requirements.txt